USE testdb;

CREATE TABLE IF NOT EXISTS agents (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(40),
  WORKING_AREA VARCHAR(35),
  COMMISSION DOUBLE,
  PHONE_NO VARCHAR(15),
  COUNTRY VARCHAR(25)
);

INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Ramasundar', 'Bangalore', '0.15', '077-25814763', 'India');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Alex ', 'London', '0.13', '075-12458969', 'UK');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Alford', 'New York', '0.12', '044-25874365', 'USA');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Ravi Kumar', 'Bangalore', '0.15', '077-45625874', 'India');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Santakumar', 'Chennai', '0.14', '007-22388644', 'India');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Lucida', 'San Jose', '0.12', '044-52981425', 'USA');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Anderson', 'Brisban', '0.13', '045-21447739', 'Australia');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Subbarao', 'Bangalore', '0.14', '077-12346674', 'India');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Mukesh', 'Mumbai', '0.11', '029-12358964', 'India');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('McDen', 'London', '0.15', '078-22255588', 'UK');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Ivan', 'Toronto', '0.15', '008-22544166', 'Canada');
INSERT INTO AGENTS(NAME,WORKING_AREA,COMMISSION,PHONE_NO,COUNTRY) VALUES ('Benjamin', 'Hampshair', '0.11', '008-22536178', 'UK');
